version: '1.0'
services:
  app:
    image: frontend
    container_name: frontend
    build:
      context: ./
      target: builder
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"