name: ci
on:
  workflow_dispatch: 
  push:
    branches:
      - "main"

jobs:
  pull:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    
  build:
      runs-on: self-hosted
      needs: pull
      steps:
      - name: Check docker containers 
        run: cd ../../../ && ls



