name: ci
on:
  workflow_dispatch: 
  push:
    branches:
      - "main"

jobs:
  pull:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    
  build:
      runs-on: self-hosted
      needs: pull
      steps:
      - name: Check docker containers 
        run: docker ps && pm2 list
      - name: Install node modules
        run: npm install --force
      - name: Build 
        run: npm run build
      - name: Remove frontend container 
        continue-on-error: true
        run: pm2 start npm --name frontend -- start
      - name: Reload frontend  
        continue-on-error: true
        run: pm2 reload frontend
      - name: All stoped containers restart
        continue-on-error: true
        run: docker restart $(docker ps -a -q)



