name: ci
on:
  workflow_dispatch: 
  push:
    branches:
      - "main"

jobs:
  pull:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    
  build:
      runs-on: self-hosted
      needs: pull
      steps:
      - name: Check docker containers and pm2 apps
        run: docker ps && pm2 list
      - name: Stop all containers 
        continue-on-error: true
        run: docker stop $(docker ps -q) 
      - name: .env transfer
        run: cd ../../../ && cp .env ./_work/frontend/frontend  
      - name: ls
        run: ls && cat .env
      - name: Install node modules
        run: npm install --force
      - name: Build 
        run: npm run build
      - name: delete frontend  
        continue-on-error: true
        run: pm2 delete frontend
      - name: Start frontend  
        run: sleep 20s && npm start
      - name: All stoped containers restart
        continue-on-error: true
        run: docker restart $(docker ps -a -q)



